Feat - routine modal UI 구현
longlivedrgn/GoodMorning pull request #18
Opened 2023-08-28 02:00 UTC by SunnnySong

안녕하세요 미로! 처음 시도해보는 UI 구현이 많아 약간 긴장을 하면서 구현을 했었던 것 같아요 ㅋㅋ
역시나 제가 예상한 시간보다 훨씬 더 걸리더라구요! ㅋㅋㅋㅋㅋ 그럼 차근 차근 제가 겪었던 문제들에 대해 이야기해볼게요!

# 구현화면
| iPhone 14 pro | iPhone SE3 |
| --- | --- |
|<img src="https://github.com/longlivedrgn/GoodMorning/assets/85678496/1c4b6149-4618-4e5b-8bac-8d999c28fa8b" width="250"/>|<img src="https://github.com/longlivedrgn/GoodMorning/assets/85678496/8a6838f4-518d-44c4-8f59-a0c97771e8c9" width="250"/>|
----

## 중요도 깃발 UI 구현하기
중요도를 나타내는 깃발을 구현하기 위해 어떤 UI Component를 이용할까 고민이 많았어요. 

첫 번째로 생각했던 방법은 `UIButton`을 이용한 방법이에요.
- UIButton 3개를 이용해 UI를 구현
- 3개 중에 한개의 버튼만을 선택할 수 있도록 로직 구현
- 선택된 버튼과 선택되지 못한 버튼 간의 UI 변화 로직 구현
UIButton으로 구현한다면 가능할 것 같기도 했지만, 위와 같은 과정을 구현하는데 있어서 로직이 쉽지 않을 것이라 생각했어요.

그래서 생각한 방법은 기존 UI Components에 있으면서도, 여러 개의 버튼을 컨트롤 가능한 [UISegmentedControl](https://developer.apple.com/documentation/uikit/uisegmentedcontrol)을 사용하기로 결정했어요.

하지만 UISegmentedControl을 custom하는 과정은 쉽지 않았어요ㅜㅜ
- 일단, 기존에 적용되어있는 divider과 background 색상을 흰색으로 변경해주었어요.
```swift
private func removeBackgroundColor() {
    let image = UIImage()

    self.setBackgroundImage(image, for: .normal, barMetrics: .default)
    self.setBackgroundImage(image, for: .selected, barMetrics: .default)
    self.setBackgroundImage(image, for: .highlighted, barMetrics: .default)
    self.setDividerImage(
        image,
        forLeftSegmentState: .selected,
        rightSegmentState: .normal,
        barMetrics: .default
    )
}
```
- 3개 중에 하나의 깃발을 클릭했을 때, 선택되지 못한 깃발은 투명도를 조절해 주어야 해요.
- 해당 로직 구현을 위해 `UISegmentedControl`에 내장되어있는 `selectedSegmentIndex`을 사용하려 했어요.
    - 하지만 해당 속성은  UISegmentedControl이 처음 init 되었을 때만 설정이 가능하고, 사용자 입력에 따라 변경되지는 않았어요.
    - 그래서 `selectedIndex` 속성을 만들어 준 뒤, didSet을 설정해 깃발의 image 설정을 추가해주었어요.
- UIImage에는 alpha값을 변경해주는 함수가 없기 때문에 extension으로 추가해 주었어요.
----

## 이모지 UITextField 구현하기
이모지 부분을 클릭하면, 한글이나 영어 키보드 대신 이모지 키보드가 올라와야 해요. 해당 부분은 아래와 같은 코드로 구현했어요.
```swift
 override var textInputMode: UITextInputMode? {
        for mode in UITextInputMode.activeInputModes where mode.primaryLanguage == "emoji" {
            return mode
        }
        return nil
    }
```
그리고 딱 한 개의 이모지만 받기 위해 `UITextFieldDelegate` 함수를 사용했어요.
- 이모지 부분에 공백을 주지 않기 위해 이모지  기본값을 설정했어요.
- 이모지를 수정하는 과정 중에 지우기 버튼을 누르면 이모지가 공백으로 설정되기 때문에 UITextField에 새로 들어온 값이 빈 값이라면 기본 이모지 값을 넣어 줄 수 있도록 구현했어요.

이모지 UITextField를 수정하려고 누르면, UICollectionView 관련 메세지가 발생하는 문제가 있어요. 그런데 해당 UIViewController에서는 UICollectionView를 사용하지 않았어요. (무슨 문제일까요..?) 이 부분에 대해서는 조금 더 고민을 해봐야 할 듯 합니다😭

2023-08-29 08:49 UTC, longlivedrgn requested changes
써니! 고생많으셨습니다!~ 이모지 구현이랑 segmentedControl 구현을 어떤 식으로 할 지 고민이되었는데, 엄청 잘 구현해주셨네요!

고생하셨습니다!🙇‍♂️

2023-08-29 08:49 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +        }
혹시 써니 이 부분은 if let으로 구현하신 이유가 있으시나요?!🧐
다른 곳은 다 guard문으로 구현하셨는데, 여기서만 if let을 사용하셔서 궁금해서 여쭤봅니다!

2023-08-29 08:49 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +    }
써니 이 부분은 자신만의 기준으로 네이밍을 하는 것 같은데요!
저 같은 경우에는 didDeleteButtonTapped() - did - 주어 - 동사 순서로 네이밍을 하고, 써니는 동사 - 주어 형태로 네이밍을 하더라고요.

그래서 같이 통일하면 좋을 거 같은데, 대부분의 코드에서 action 함수에대해서는 아래와 같이 네이밍을 하는 것 같더라구요!

Action 함수의 네이밍은 '주어 + 동사 + 목적어' 형태를 사용합니다.

- *Tap(눌렀다 뗌)*은 UIControlEvents의 `.touchUpInside`에 대응하고, *Press(누름)*는` .touchDown`에 대응합니다.
- `will~`은 특정 행위가 일어나기 직전이고, `did~`는 특정 행위가 일어난 직후입니다.
- `should~`는 일반적으로 Bool을 반환하는 함수에 사용됩니다.

**좋은 예**
```swift
func backButtonDidTap() {
  // ...
}
```

**나쁜 예**
```swift
func back() {
  // ...
}

func pressBack() {
  // ...
}
```

저희도 이렇게 네이밍을 해보면 어떨 까 싶어서요!ㅎㅎ

2023-08-29 08:49 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +            emoji.delegate = self
혹시 여기서 `clipsToBounds`를 true로 설정하신 이유가 무엇인 지 궁금합니다!🙋🏻‍♂️

2023-08-29 08:49 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +}
이렇게 이모지 키보드를 구현할 수 있다는 점이 정말 신기하네요!!😄 고생하셨습니다!!~
여기서 제가 궁금한 점이 있는데요! 혹시 아래와 같이 구현해도 문제가 없을까요? return true를 탈 경우가 없지 않나해서요! (현재 emoji textfield 말고는 다른 textfield는 해당 delegate 메소드를 활용하지 않으니까요!)

또한, 현재 상태에서는 한글 자판으로 넘어가면 한글을 작성할 수 있더라고요!  그래서 Character extension을 통해서 이모지인 지 확인하는 과정을 가지는 것이 어떨까합니다! ☺️

관련 블로그 글: https://betterprogramming.pub/understanding-swift-strings-characters-and-scalars-a4b82f2d8fde

```suggestion

extension TODOModalViewController: UITextFieldDelegate {

    func textField(
        _ textField: UITextField,
        shouldChangeCharactersIn range: NSRange,
        replacementString string: String
    ) -> Bool {
        guard Character(string).isEmoji else { return false }

        if string.count == 0 {
            // 만약 이모티콘이 비었으면 기본값으로 설정.
            textField.text = "😀"
            return false
        } else {
            textField.text = string
            return false
        }
    }

}

extension Character {

    var isEmoji: Bool {
        guard let firstScalar = unicodeScalars.first else {
            return false
        }
        return firstScalar.properties.isEmoji && firstScalar.value > 0x238C
    }

}
```

2023-08-29 08:49 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Views/PrioritySegmentedControl.swift
> +
저도 `selectedSegmentIndex`를 override해서 didSet을 해보려구 했는데, init될 때만 설정 가능한가 보네요!..

저도 간단하게 button으로 구현할 수 있지 않을까 했는데, segmented control을 활용해본 게 너무 좋은 거 같습니다! 💪

2023-08-29 08:49 UTC, longlivedrgn commented on GoodMorning/GoodMorning/Extensions/UIImage+.swift
> +
알파 값을 이렇게 구현한 것도 신기하고 좋네요!👍

2023-09-01 08:29 UTC, SunnnySong commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +        }
해당 코드 이후에 추가로 작성된 코드는 없지만 만약 이 부분을 guard문으로 구현하고, `sheetPresentationController`이 nil이라면 그 이후 코드는 아예 실행조차 되지 못하고 함수가 종료될 수 있어요. 
때문에 해당 부분은 if-let으로 구현했어요! 
그리고 If-let을 사용함으로써 클로저 안에 sheetPresentationController에 관한 설정을 캡슐화 할 수 있다는 점도 장점이라고 생각해요!

2023-09-01 08:38 UTC, SunnnySong commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +    }
오! Action 함수의 네이밍 통일 너무 좋은 아이디어 같습니다!
혹시 네이밍 자료 관련 링크를 알 수 있을까요? 컨벤션 관련 노션에 링크와 함께 정리하면 좋을 것 같아요!
해당 부분 커밋 완료하였습니다!
> 커밋 : cc18711aafc344c881ae175b6cf476d332e11361

2023-09-01 08:40 UTC, SunnnySong commented on GoodMorning/GoodMorning/TODOModalScene/Views/PrioritySegmentedControl.swift
> +
UIButton의 isSelected 처럼 override하면 될 줄 알았는데 selectedSegmentIndex는 안되더라구요 ㅠㅠ 왜 안되는지 이유가 궁금하긴 합니다,,

2023-09-01 08:40 UTC, SunnnySong commented on GoodMorning/GoodMorning/Extensions/UIImage+.swift
> +
ㅋㅋㅋ 저는 이번에 UIImage에 알파 값 조정이 없다는 것도 처음 알앗어요!

2023-09-02 13:34 UTC, SunnnySong commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +            emoji.delegate = self
clipsToBounds를 하지 않았을 경우 화면은 아래와 같아요!

<img width="300" alt="스크린샷 2023-09-02 오후 10 31 50" src="https://github.com/longlivedrgn/GoodMorning/assets/85678496/e9bd341b-e996-4aa8-aab7-7238af7a6b17">

emoji textField와 title textField가 하나의 UIStackView로 묶이는데, 두 개의 높이가 서로 달라요.(두 textField의 font size가 다르기 때문) 그래서 emoji textField에서 전체 UIStackView 범위를 넘어가는 부분은 자르기 위해 clipsToBounds를 true로 설정했어요!

<img width="300" alt="스크린샷 2023-09-02 오후 10 34 36" src="https://github.com/longlivedrgn/GoodMorning/assets/85678496/c33d551f-45b7-4ccd-8ec1-b86dd8de9767">

2023-09-02 14:00 UTC, SunnnySong commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +}
오! return true를 탈 경우가 없다는 미로의 말에 동의합니다! 그런데 생각해보니 string.count == 0일 때 기본값 이모지를 설정하는 것 보다, string.count == 0일 때 return false로 설정하는 것이 더 좋겠다는 생각이 들었어요. 삭제는 안되고 새로운 값을 눌러야 값이 변경되는 것이죠!

이모지가 아닌 입력값이 들어왔을 때 관련한 구현은 수정 완료했습니다! 스칼라 코드를 사용해 입력값이 이모지인지 아닌지 확인하는 방법이 매우 좋다고 생각해요👍🏻
> 커밋 : 596f69afd0716e67ad8add23159f16a97ad86763

2023-09-03 08:52 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +        }
오 그런 의미가 있었군요!
early exit이 이유가 아니라면 이렇게 구현을 해도 괜찮을 거 같다는 생각이 드네요!
```swift
self.sheetPresentationController?.detents = [.medium()]
```

매우 사소한 부분이고 써니 코드에서 굳이 바꿀 필요도 없는데 sheetPresentationController에서만 if let을 활용한 이유가 궁금했어요!

2023-09-03 09:02 UTC, longlivedrgn commented on GoodMorning/GoodMorning/TODOModalScene/Controllers/TODOModalViewController.swift
> +            emoji.delegate = self
우와아 이 부분은 생각 못했네요!.. 봤을 때 UI적으로 큰 차이가 없는 거 같았는데, fontSize에 따라서 높이 달라진다는 것을 간과했네요!  superview 테두리로 잘라버리는 것이 훨씬 좋네요! 👍

2023-09-05 08:32 UTC, merged